<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay</name>
   <tag></tag>
   <elementGuidId>0d7da0a3-39b2-4a78-8a61-aeb5b3eacd84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Pay&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a578fca2-f484-4a98-a668-2d63b9053c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e44522ca-1e76-4aed-ad86-e8b0aefc34a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-btn-bg relative flex justify-center items-center focus:outline-none ring-transparent cursor-pointer bmc-btn-wrapper-9 font-cr-bold w-full h-12 px-5 text-white tw-dark-color-rounded-full mt-6</value>
      <webElementGuid>2777658a-87e3-4fb4-9975-8911a7c0cc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay</value>
      <webElementGuid>f960cde7-18c5-4065-937a-96956a8a1c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-ctr-page&quot;)/div[@class=&quot;z-50 fixed inset-0 overflow-y-auto w-full h-full fade-in-modal&quot;]/div[@class=&quot;fixed inset-0 z-10 w-screen overflow-y-auto&quot;]/div[@class=&quot;w-full flex justify-center items-center overflow-y-auto min-h-full xs:items-end&quot;]/div[@class=&quot;tw-modal-content relative m-auto my-12 tw-active-modal xs:my-0 xs:w-full&quot;]/div[@class=&quot;w-112.5 bg-white rounded-3xl mt-8 xs:w-full xs:pt-8 xs:rounded-b-none xs:mt-20 p-8 xs:p-4&quot;]/div[1]/div[3]/div[@class=&quot;mt-5&quot;]/div[1]/button[@class=&quot;tw-btn-bg relative flex justify-center items-center focus:outline-none ring-transparent cursor-pointer bmc-btn-wrapper-9 font-cr-bold w-full h-12 px-5 text-white tw-dark-color-rounded-full mt-6&quot;]</value>
      <webElementGuid>1d7a9683-5cd9-47f9-8c05-c8c8d7e83bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>5cb509fe-4279-44bf-a5a9-bb4df049a265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-ctr-page']/div[3]/div[2]/div/div/div/div/div[3]/div[2]/div/button</value>
      <webElementGuid>22fbb395-1db2-4016-ae58-34608c581420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5'])[1]/following::button[1]</value>
      <webElementGuid>79ed47dc-f65f-48d2-96a7-708419d338a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button</value>
      <webElementGuid>a5e81ac4-0e10-4c72-a289-52dd3ddb21dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Pay' or . = 'Pay')]</value>
      <webElementGuid>1e20c5cc-7bb9-4b1b-bdbb-2978351cda88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
