<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Checkout_cursor-pointer rounded-full fl_cc8274</name>
   <tag></tag>
   <elementGuidId>cfbb8732-7c4d-4304-b302-12befa1b4cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tw-ctr-page']/div[3]/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.w-112\.5 > div > div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efcee1b3-d81c-4315-ae07-e314d434f24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-full flex items-center justify-center tw-scale-on-hover close-bg-transition hover:before:bg-dark/5 w-8 h-8 absolute right-4 top-12 xs:top-24 xs:top-22</value>
      <webElementGuid>be2d0b0a-33c9-44d3-b97e-249664180131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-ctr-page&quot;)/div[@class=&quot;z-50 fixed inset-0 overflow-y-auto w-full h-full fade-in-modal&quot;]/div[@class=&quot;fixed inset-0 z-10 w-screen overflow-y-auto&quot;]/div[@class=&quot;w-full flex justify-center items-center overflow-y-auto min-h-full xs:items-end&quot;]/div[@class=&quot;tw-modal-content relative m-auto my-12 tw-active-modal xs:my-0 xs:w-full&quot;]/div[@class=&quot;w-112.5 bg-white rounded-3xl mt-8 xs:w-full xs:pt-8 xs:rounded-b-none xs:mt-20 p-8 xs:p-4&quot;]/div[1]/div[@class=&quot;cursor-pointer rounded-full flex items-center justify-center tw-scale-on-hover close-bg-transition hover:before:bg-dark/5 w-8 h-8 absolute right-4 top-12 xs:top-24 xs:top-22&quot;]</value>
      <webElementGuid>bc4bd24f-baf0-4f34-b70d-c96f43649633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-ctr-page']/div[3]/div[2]/div/div/div/div/div</value>
      <webElementGuid>513b9705-08cd-4698-b3f7-f2e4c847f548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::div[8]</value>
      <webElementGuid>1d95b2bd-f6ae-4c39-8df2-5dc70b825eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Testing Board'])[3]/preceding::div[2]</value>
      <webElementGuid>53be8c07-fade-4405-b62f-c23399e27502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div</value>
      <webElementGuid>65ae2ed0-cd82-4e90-95a1-ecdcff7639ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
