<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_5_w-full tw-remove-default-styling tw_fa2b0a</name>
   <tag></tag>
   <elementGuidId>b8d4e24f-b234-4971-9cb3-b36ec8bab577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c5ada3-6604-4c85-bc4b-d4b9943c786b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full tw-remove-default-styling tw-input-common cursor-text font-cr-medium placeholder:font-cr-book tw-box-common-v2 focus:!border-dark</value>
      <webElementGuid>e0ca912c-d10e-4fdd-a304-882ff35f4768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>6c86bf3d-f311-4e1c-9e90-5b2ade342386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2af46895-ae07-4417-949d-f4f7c1981958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tw-ctr-page&quot;)/div[@class=&quot;z-50 fixed inset-0 overflow-y-auto w-full h-full fade-in-modal&quot;]/div[@class=&quot;fixed inset-0 z-10 w-screen overflow-y-auto&quot;]/div[@class=&quot;w-full flex justify-center items-center overflow-y-auto min-h-full xs:items-end&quot;]/div[@class=&quot;tw-modal-content relative m-auto my-12 tw-active-modal xs:my-0 xs:w-full&quot;]/div[@class=&quot;w-112.5 bg-white rounded-3xl mt-8 xs:w-full xs:pt-8 xs:rounded-b-none xs:mt-20 p-8 xs:p-4&quot;]/div[1]/div[3]/div[@class=&quot;mt-5&quot;]/div[1]/div[1]/input[@class=&quot;w-full tw-remove-default-styling tw-input-common cursor-text font-cr-medium placeholder:font-cr-book tw-box-common-v2 focus:!border-dark&quot;]</value>
      <webElementGuid>0b91ce53-b2c3-4ecf-836f-6b636a419845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='email']</value>
      <webElementGuid>59c3cf2b-5bab-493a-bc4c-ad0891658212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tw-ctr-page']/div[3]/div[2]/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>d22d1be3-5632-4b23-b295-f8a4328d2fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>ad745781-3c1e-40ac-a22f-30a5202c5361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>71f0b158-3f80-4474-a317-1e05fd1e7abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
