<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jackets</name>
   <tag></tag>
   <elementGuidId>33c3f543-cf94-4d8f-8115-648ec90dfd2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[4]/div[2]/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Jackets&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e36ec081-cfa1-4d03-8493-b2f2e7127862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html</value>
      <webElementGuid>23d6bfc1-948c-40b1-8f23-17687cb1aa41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jackets</value>
      <webElementGuid>992d26ca-7ad7-4dd1-a707-15aa6127a2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;sidebar sidebar-main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;categories-menu&quot;]/ul[@class=&quot;items&quot;]/li[@class=&quot;item&quot;]/a[1]</value>
      <webElementGuid>3811ec0a-e308-452f-80f0-62221257752d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[4]/div[2]/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>514f544e-aeee-49ab-8bcf-9ceb76320e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jackets')]</value>
      <webElementGuid>8efba966-9cf1-4926-aca9-8a281dd045c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoodies &amp; Sweatshirts'])[3]/following::a[1]</value>
      <webElementGuid>676901b0-6243-457c-b08e-cd66083e7523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[4]/following::a[2]</value>
      <webElementGuid>75d9431d-d4a4-474e-8ec7-fa2b1c34781e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tees'])[3]/preceding::a[1]</value>
      <webElementGuid>7f769fe2-569e-4fba-8f06-b3d4fec7e85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanks'])[2]/preceding::a[2]</value>
      <webElementGuid>bc7f1cd5-f69b-4b24-b1c8-a08b33a76cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html')])[2]</value>
      <webElementGuid>75c79804-d21d-40e4-966f-96ab97574497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>eb547c6b-df12-4d22-9f49-f48ce42b13a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/men/tops-men/jackets-men.html' and (text() = 'Jackets' or . = 'Jackets')]</value>
      <webElementGuid>55dc4446-c50a-4f0d-af5d-83a90f6bdccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
