<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_000017527</name>
   <tag></tag>
   <elementGuidId>cd7098aa-78dc-4ed3-8c1b-e4702c91d7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.order-number > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[2]/p/a/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;000017527&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>14c9fd18-b974-4164-8ba0-0115292d62ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000017527</value>
      <webElementGuid>3382c851-0258-4213-96d7-9185fc564f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;checkout-success&quot;]/p[1]/a[@class=&quot;order-number&quot;]/strong[1]</value>
      <webElementGuid>727e6cb3-e01d-4558-8ce3-f61e9f8ccf3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/p/a/strong</value>
      <webElementGuid>69e35ed7-f1d3-419f-85d1-a178b1fe9f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print receipt'])[1]/following::strong[1]</value>
      <webElementGuid>c21d71be-6d74-4675-8966-9f46682b1230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for your purchase!'])[1]/following::strong[1]</value>
      <webElementGuid>60eb6906-e828-4e7d-928e-eaf9be17c5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/preceding::strong[1]</value>
      <webElementGuid>81f7063d-15fd-48cc-8abd-50a92a06ada7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='000017527']/parent::*</value>
      <webElementGuid>71abbdc5-6093-4ee4-a114-7c7a0a83995f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/strong</value>
      <webElementGuid>d6567be6-e3ba-45f3-9f48-fa76af28c542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '000017527' or . = '000017527')]</value>
      <webElementGuid>8616dcb5-d339-4eb3-bfbe-73cfdfd3bab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
